### PR TITLE
Added cvector_reserve macro

### PR DESCRIPTION
**Pull request by marekmosna**
Request a change in capacity
Requests that the vector capacity be at least enough to contain n elements.

If n is greater than the current vector capacity, the function causes the container to reallocate its storage increasing its capacity to n (or greater).

In all other cases, the function call does not cause a reallocation and the vector capacity is not affected.

This function has no effect on the vector size and cannot alter its elements.

### CODE REVIEW

**Comment by marekmosna** [comment]
My apologies for the `test.c ` but please try to avoid tabs and replace them by space

**Comment by andy5995** [comment]
> My apologies for the `test.c ` but please try to avoid tabs and replace them by space

@eteran seems to prefer tabs to spaces in this project. The header file and example.c use tabs as well.

Although the [.editorconfig](https://github.com/eteran/c-vector/blob/35858f15936a10e6eb8a871e9e4d8ed447aa54b9/.editorconfig) has spaces specified. Probably if tabs are replaced with spaces, it needs to happen in every file, and in a separate PR.

**Comment by andy5995** [comment]
> > My apologies for the `test.c ` but please try to avoid tabs and replace them by space
> 
> @eteran seems to prefer tabs to spaces in this project. The header file and example.c use tabs as well.
> 
> Although the [.editorconfig](https://github.com/eteran/c-vector/blob/35858f15936a10e6eb8a871e9e4d8ed447aa54b9/.editorconfig) has spaces specified. Probably if tabs are replaced with spaces, it needs to happen in every file, and in a separate PR.

But of course that's all up to @eteran, I was just throwing in my observation and 2 cents. ;)

**Comment by marekmosna** [comment]
> > My apologies for the `test.c ` but please try to avoid tabs and replace them by space
> 
> @eteran seems to prefer tabs to spaces in this project. The header file and example.c use tabs as well.
> 
> Although the [.editorconfig](https://github.com/eteran/c-vector/blob/35858f15936a10e6eb8a871e9e4d8ed447aa54b9/.editorconfig) has spaces specified. Probably if tabs are replaced with spaces, it needs to happen in every file, and in a separate PR.

Yeah it's absolutely should be in another PR, my apologies. But I hope that this file will become obsolete and replaced by any unit testing file based on selected framework as soon as possible. I'm planning to use this implementation in my projects and I have to insist on proper unit tests.

**Comment by eteran** [comment]
This looks pretty good!

@andy5995 @marekmosna ... yeah, I think I'll just use spaces for this project :-P. I'll also add a clang-format file too so the matter can be done with unambiguously.

I'll look to merge this in once I take care of that ;-)

**Comment by marekmosna** [comment]
> This looks pretty good!
> 
> @andy5995 @marekmosna ... yeah, I think I'll just use spaces for this project :-P. I'll also add a clang-format file too so the matter can be done with unambiguously.
> 
> I'll look to merge this in once I take care of that ;-)

Perfect...standardized formatting is always appreciated. Another stage in CI does the great job to check.

**Pull request closed without merging**
