### PR TITLE
remove unneeded build targets from the cmake file

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by eteran** [comment]
So I'm not sure I agree with this PR. Even though this is a single header library, I do want people to have the option to do the "cmake thing" and include this in there project as a submodule and do things like:

```
add_directory(c-vector)
target_link_libraries(my_app, c-vector)
```

And cmake would make there app automatically find the headers. Sure, it's unecessary because you can just copy the .h wherever, but I've definitely worked with people who like a little extra organization.

**Comment by andy5995** [comment]
I think I get what you're saying and it makes sense about being able to include your cmake, but because the header would need to be #included by the developer in order to use the functions, it will get built anyway (even if target_link_libraries isn't used). though I could be missing something. Based on your code, I'm not as experienced as you and I've never written a header-only library.

**Comment by eteran** [comment]
I'll explain what I mean, having the cmake target lets developers have a directory structure like this:

/src/main.cpp
/src/CMakeLists.txt
/third-party/CMakeLists.txt
/third-party/c-vector/...
/CMakeLists.txt

Where the main CMakeLists is a small file that looks something like this::

```
add_subdirectory(src)
add_subdirectory(third-party)
```

and third-party/CMakeLists.txt might look like this:

```
add_subdirectory(c-vector)
```

And even though the src directory is far removed from the c-vector logically, the src cmake can just do:

```
target_link_libraries(my_project c-vector)
```

And cmake will generate an include path that gives it access to the `c-vector` header. This is considered desireable if you have many third-party libs and you want to be able to update them simply by replacing individual directories with new copies.

**Comment by andy5995** [comment]
Oh, I see what you mean now. I think I wasn't understanding all of what that function does. I'm not really much of cmake guy, I'm more of an @mesonbuild guy :) Again, thanks for the explanation.

**Pull request closed without merging**
