### PR TITLE
Random access

### PR DESCRIPTION
**Pull request by lukepalmer**
Support sparse vectors and setting the vector by index
clang-format

### CODE REVIEW

**Comment by eteran** [comment]
Thanks for your contribution!

A few thoughts though.

The first thing is that I disagree with the unused capacity being zero-initialized. When used correctly, 
space should never be at risk of being used before initialization. So the zeroing is just redundant work.

And I also not sure how I feel about the vector supporting "sparse" indexes, since the goal of this is to be similar in concept to `std::vector` from c++. I kinda feel like that should be in a "sparse vector" library.

So I'll take a careful look at this but I'm unsure if it'll end up being applied.

**Comment by lukepalmer** [comment]
Yes, entirely see your point about initialization. You only need it if you care about being able to set / get sparsely, with nulls in between. So those go together.

Thank you for taking a look!

**Comment by eteran** [comment]
So, I'm going to be doing a "partial apply" for two reasons.

1. This PR came in around the same time as another, both of which do "stylistic" fixups. So I'll definitely keep that part.

2. I don't think that **this** library should be a "sparse vector", but I can see the utility. I might end up making a second header which adds that particular feature separately.

So this PR will be closed, but I will be manually doing some of the cleanups that you did (for example using a variable to avoid recalculating sizes and similar).

Thanks again!

**Comment by lukepalmer** [comment]
Sounds good to me. 

My one comment is that it'd be nice to use something standard for formatting (like clang-format). Looking at forks out there most people change formatting, and it'd be good to pick something common.

**Pull request closed without merging**
